export const months = [
  "JAN",
  "FEB",
  "MAR",
  "APR",
  "MAY",
  "JUN",
  "JULY",
  "AUG",
  "SEP",
  "OCT",
  "NOV",
  "DEC",
];

export const statuses = [
  "Customer/Public Holiday",
  "Present",
  "Leave",
  "Other",
  "Half Day",
];

export const dateData = [
  { date: "1-AUG-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "2-AUG-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "3-AUG-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "4-AUG-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "5-AUG-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "6-AUG-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "7-AUG-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "8-AUG-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "9-AUG-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "10-AUG-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "11-AUG-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "12-AUG-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "13-AUG-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "14-AUG-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "15-AUG-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "16-AUG-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "17-AUG-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "18-AUG-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "19-AUG-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "20-AUG-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "21-AUG-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "22-AUG-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "23-AUG-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "24-AUG-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "25-AUG-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "26-AUG-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "27-AUG-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "28-AUG-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "29-AUG-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "30-AUG-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "31-AUG-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "1-SEP-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "2-SEP-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "3-SEP-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "4-SEP-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "5-SEP-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "6-SEP-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "7-SEP-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "8-SEP-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "9-SEP-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "10-SEP-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "11-SEP-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "12-SEP-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "13-SEP-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "14-SEP-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "15-SEP-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "16-SEP-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "17-SEP-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "18-SEP-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "19-SEP-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "20-SEP-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "21-SEP-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "22-SEP-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "23-SEP-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "24-SEP-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "25-SEP-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "26-SEP-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "27-SEP-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "28-SEP-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "29-SEP-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "30-SEP-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "1-OCT-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "2-OCT-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "3-OCT-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "4-OCT-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "5-OCT-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "6-OCT-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "7-OCT-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "8-OCT-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "9-OCT-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "10-OCT-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "11-OCT-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "12-OCT-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "13-OCT-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "14-OCT-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "15-OCT-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "16-OCT-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "17-OCT-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "18-OCT-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "19-OCT-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "20-OCT-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "21-OCT-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "22-OCT-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "23-OCT-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "24-OCT-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "25-OCT-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "26-OCT-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "27-OCT-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "28-OCT-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "29-OCT-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "30-OCT-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "31-OCT-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "1-NOV-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "2-NOV-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "3-NOV-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "4-NOV-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "5-NOV-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "6-NOV-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "7-NOV-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "8-NOV-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "9-NOV-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "10-NOV-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "11-NOV-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "12-NOV-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "13-NOV-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "14-NOV-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "15-NOV-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "16-NOV-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "17-NOV-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "18-NOV-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "19-NOV-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "20-NOV-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "21-NOV-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "22-NOV-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "23-NOV-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "24-NOV-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "25-NOV-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "26-NOV-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "27-NOV-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "28-NOV-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "29-NOV-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "30-NOV-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "1-DEC-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "2-DEC-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "3-DEC-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "4-DEC-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "5-DEC-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "6-DEC-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "7-DEC-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "8-DEC-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "9-DEC-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "10-DEC-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "11-DEC-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "12-DEC-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "13-DEC-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "14-DEC-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "15-DEC-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "16-DEC-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "17-DEC-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "18-DEC-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "19-DEC-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "20-DEC-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "21-DEC-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "22-DEC-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "23-DEC-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "24-DEC-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "25-DEC-2022",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "26-DEC-2022", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "27-DEC-2022", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "28-DEC-2022", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "29-DEC-2022", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "30-DEC-2022", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "31-DEC-2022",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "1-JAN-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "2-JAN-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "3-JAN-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "4-JAN-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "5-JAN-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "6-JAN-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "7-JAN-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "8-JAN-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "9-JAN-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "10-JAN-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "11-JAN-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "12-JAN-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "13-JAN-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "14-JAN-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "15-JAN-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "16-JAN-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "17-JAN-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "18-JAN-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "19-JAN-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "20-JAN-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "21-JAN-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "22-JAN-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "23-JAN-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "24-JAN-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "25-JAN-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "26-JAN-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "27-JAN-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "28-JAN-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "29-JAN-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "30-JAN-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "31-JAN-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "1-FEB-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "2-FEB-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "3-FEB-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "4-FEB-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "5-FEB-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "6-FEB-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "7-FEB-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "8-FEB-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "9-FEB-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "10-FEB-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "11-FEB-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "12-FEB-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "13-FEB-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "14-FEB-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "15-FEB-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "16-FEB-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "17-FEB-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "18-FEB-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "19-FEB-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "20-FEB-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "21-FEB-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "22-FEB-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "23-FEB-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "24-FEB-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "25-FEB-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "26-FEB-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "27-FEB-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "28-FEB-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "1-MAR-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "2-MAR-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "3-MAR-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "4-MAR-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "5-MAR-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "6-MAR-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "7-MAR-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "8-MAR-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "9-MAR-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "10-MAR-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "11-MAR-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "12-MAR-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "13-MAR-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "14-MAR-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "15-MAR-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "16-MAR-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "17-MAR-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "18-MAR-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "19-MAR-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "20-MAR-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "21-MAR-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "22-MAR-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "23-MAR-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "24-MAR-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "25-MAR-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "26-MAR-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "27-MAR-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "28-MAR-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "29-MAR-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "30-MAR-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "31-MAR-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "1-APR-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "2-APR-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "3-APR-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "4-APR-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "5-APR-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "6-APR-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "7-APR-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "8-APR-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "9-APR-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "10-APR-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "11-APR-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "12-APR-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "13-APR-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "14-APR-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "15-APR-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "16-APR-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "17-APR-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "18-APR-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "19-APR-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "20-APR-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "21-APR-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "22-APR-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "23-APR-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "24-APR-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "25-APR-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "26-APR-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "27-APR-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "28-APR-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "29-APR-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "30-APR-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "1-MAY-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "2-MAY-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "3-MAY-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "4-MAY-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "5-MAY-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "6-MAY-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "7-MAY-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "8-MAY-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "9-MAY-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "10-MAY-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "11-MAY-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "12-MAY-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "13-MAY-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "14-MAY-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "15-MAY-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "16-MAY-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "17-MAY-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "18-MAY-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "19-MAY-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "20-MAY-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "21-MAY-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "22-MAY-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "23-MAY-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "24-MAY-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "25-MAY-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "26-MAY-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "27-MAY-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "28-MAY-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "29-MAY-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "30-MAY-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "31-MAY-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "1-JUN-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "2-JUN-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "3-JUN-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "4-JUN-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "5-JUN-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "6-JUN-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "7-JUN-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "8-JUN-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "9-JUN-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "10-JUN-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "11-JUN-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "12-JUN-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "13-JUN-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "14-JUN-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "15-JUN-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "16-JUN-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "17-JUN-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "18-JUN-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "19-JUN-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "20-JUN-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "21-JUN-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "22-JUN-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "23-JUN-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "24-JUN-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "25-JUN-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "26-JUN-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "27-JUN-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "28-JUN-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "29-JUN-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "30-JUN-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "1-JUL-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "2-JUL-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "3-JUL-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "4-JUL-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "5-JUL-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "6-JUL-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "7-JUL-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "8-JUL-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "9-JUL-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "10-JUL-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "11-JUL-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "12-JUL-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "13-JUL-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "14-JUL-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "15-JUL-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "16-JUL-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "17-JUL-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "18-JUL-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "19-JUL-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "20-JUL-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "21-JUL-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "22-JUL-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "23-JUL-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "24-JUL-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "25-JUL-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "26-JUL-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "27-JUL-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "28-JUL-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "29-JUL-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "30-JUL-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "31-JUL-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "1-AUG-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "2-AUG-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "3-AUG-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "4-AUG-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "5-AUG-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "6-AUG-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "7-AUG-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "8-AUG-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "9-AUG-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "10-AUG-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "11-AUG-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "12-AUG-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "13-AUG-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "14-AUG-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "15-AUG-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "16-AUG-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "17-AUG-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "18-AUG-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "19-AUG-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "20-AUG-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "21-AUG-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "22-AUG-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "23-AUG-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "24-AUG-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "25-AUG-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "26-AUG-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "27-AUG-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "28-AUG-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "29-AUG-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "30-AUG-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "31-AUG-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "1-SEP-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "2-SEP-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "3-SEP-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "4-SEP-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "5-SEP-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "6-SEP-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "7-SEP-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "8-SEP-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "9-SEP-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "10-SEP-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "11-SEP-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "12-SEP-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "13-SEP-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "14-SEP-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "15-SEP-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "16-SEP-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "17-SEP-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "18-SEP-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "19-SEP-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "20-SEP-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "21-SEP-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "22-SEP-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "23-SEP-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "24-SEP-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "25-SEP-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "26-SEP-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "27-SEP-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "28-SEP-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "29-SEP-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "30-SEP-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "1-OCT-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "2-OCT-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "3-OCT-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "4-OCT-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "5-OCT-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "6-OCT-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "7-OCT-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "8-OCT-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "9-OCT-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "10-OCT-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "11-OCT-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "12-OCT-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "13-OCT-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "14-OCT-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "15-OCT-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "16-OCT-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "17-OCT-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "18-OCT-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "19-OCT-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "20-OCT-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "21-OCT-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "22-OCT-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "23-OCT-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "24-OCT-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "25-OCT-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "26-OCT-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "27-OCT-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "28-OCT-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "29-OCT-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "30-OCT-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "31-OCT-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "1-NOV-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "2-NOV-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "3-NOV-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "4-NOV-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "5-NOV-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "6-NOV-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "7-NOV-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "8-NOV-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "9-NOV-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "10-NOV-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "11-NOV-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "12-NOV-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "13-NOV-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "14-NOV-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "15-NOV-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "16-NOV-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "17-NOV-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "18-NOV-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "19-NOV-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "20-NOV-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "21-NOV-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "22-NOV-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "23-NOV-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "24-NOV-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "25-NOV-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "26-NOV-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "27-NOV-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "28-NOV-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "29-NOV-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "30-NOV-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "1-DEC-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "2-DEC-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "3-DEC-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "4-DEC-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "5-DEC-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "6-DEC-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "7-DEC-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "8-DEC-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "9-DEC-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "10-DEC-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "11-DEC-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "12-DEC-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "13-DEC-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "14-DEC-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "15-DEC-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "16-DEC-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "17-DEC-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "18-DEC-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "19-DEC-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "20-DEC-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "21-DEC-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "22-DEC-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "23-DEC-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "24-DEC-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  { date: "25-DEC-2023", day: "Monday", status: "Present", wrkHours: "8" },
  { date: "26-DEC-2023", day: "Tuesday", status: "Present", wrkHours: "8" },
  { date: "27-DEC-2023", day: "Wednesday", status: "Present", wrkHours: "8" },
  { date: "28-DEC-2023", day: "Thursday", status: "Present", wrkHours: "8" },
  { date: "29-DEC-2023", day: "Friday", status: "Present", wrkHours: "8" },
  {
    date: "30-DEC-2023",
    day: "Saturday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
  {
    date: "31-DEC-2023",
    day: "Sunday",
    status: "Customer/Public Holiday",
    wrkHours: "",
  },
];
